---
#
# docker-compose up -d
#
# docker-compose stop
# docker-compose rm
#

#
# docker-compose stop && docker-compose rm -f
#
# rm -rf jenkins_home/ && docker build -t local/jenkins:lts . && docker-compose up -d
#

version: '3.1'

services:
  jenkins:
    image: local/jenkins:lts
    # labels:
    #   kompose.service.type: nodeport
    ports:
      # - '80:8080'
      - '8443:8443/tcp'
      - '502:20/tcp'
      - '50001:50000/tcp'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - '../git-cache:/git-cache'
    secrets:
      - sshkey
      - adminpw
      - jcacs-config.yml
    environment:
      - SEEDJOB_GIT_URL=file:///git-cache/jenkins-jobs.git
      - SEEDJOB_GIT_REF=jobs
      - CASC_JENKINS_CONFIG=/run/secrets/jcacs-config.yml

secrets:
  adminpw:
    file: ./config/adminpw.txt
  sshkey:
    file: ./config/ssh-key.pri
  jcacs-config.yml:
    file: ./config/jenkins.yml
