---
#
# docker-compose up -d
#
# docker-compose stop
# docker-compose rm
#

#
# docker-compose stop && docker-compose rm -f
#
# rm -rf jenkins_home/ && docker build -t local/jenkins:lts . && docker-compose up -d
#

version: '3.1'

services:
  jenkins:
    image: local/jenkins:lts
    # labels:
    #   kompose.service.type: nodeport
    ports:
      # - '80:8080'
      - '8081:8080/tcp'
      - '502:20/tcp'
      - '50001:50000/tcp'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - '../git-cache:/git-cache'
    secrets:
      - jenkins-user
      - jenkins-pass
      - jenkins-global-vars
    environment:
      - SEEDJOB_GIT_URL=file:///git-cache/jenkins-jobs.git
      - SEEDJOB_GIT_REF=jobs
      - JENKINS_ROOT_URL=http://localhost:8081/

# volumes:
#   jenkins_home:
#     driver: local

secrets:
  jenkins-user:
    file: ./.jenkins-user.txt
  jenkins-pass:
    file: ./.jenkins-pass.txt
  jenkins-global-vars:
    file: ./.global-vars.json
